### ISSUE TITLE
Firefox  browser loading errors

### ISSUE THREAD

**Issue by Iagea** [OBrink/DECIMER_Web#16]
When a pdf is dropped, the loading images move until the text below is written:
"The document has been uploaded and converted.
Detecting chemical structures.
This may take a few minutes. "

Then, there is no more loading GIF, which gives the impression that the webpage has frozen plus the DECIMER logo disappears momentarily.

**Comment by OBrink** [comment]
I can replicate the problem and have added a warning for Firefox users to switch to a different browser for the best user experience. Unfortunately, I do not know where to start to fix this issue.

**Comment by OBrink** [comment]
After solving the other issues with Safari, I realised that the same issue appears here, too.

**Comment by OBrink** [comment]
The issues with Firefox have been solved by adding a short timeout before sending the requests to the backend. What happened was that the request was sent before the website could load completely. Chrome/Opera/Edge appear to handle this is a better way. Here, whole parts of the website were not loading while the requests were handled.

I have come to the conclusion that the issues in Safari are a different issue. Here, the website is loading completely, but the gifs are simply not moving while a request is handled. I will open a separate issue for this problem.

The issue in Firefox is solved.
