### ISSUE TITLE
Links to GitHub repositories

### ISSUE THREAD

**Issue by Kohulan** [OBrink/DECIMER_Web#17]
Add project icons with hyperlinks to the GitHub repositories.

<img width="1140" alt="image" src="https://user-images.githubusercontent.com/30716951/166256849-6ed13b10-1526-418c-a36d-3dbd51524c8a.png">

**Comment by OBrink** [comment]
The logos with links are online. Let me know what you think, @Kohulan. If you prefer that, I can adapt the design to look more exactly like what you had suggested above.

**Comment by Kohulan** [comment]
Maybe the stout in the middle will look good. Then it is more balanced.

**Comment by OBrink** [comment]
Done
