### ISSUE TITLE
Add segmentations for images

### ISSUE THREAD

**Issue by Kohulan** [OBrink/DECIMER_Web#25]
Segment the structures out of an Image containing multiple chemical structures.
example:
https://twitter.com/drughuntersite/status/1512078242953379852

**Comment by Kohulan** [comment]
@OBrink Thanks a lot.

**Comment by egonw** [comment]
@OBrink, have you considered just converting the image to an PDF?

I just gave that a go for this Compound Chemistry infographics: https://www.compoundchem.com/2022/03/15/crocus/

And it picked up 3 (not 4!) chemicals quite well, it seems:

![image](https://user-images.githubusercontent.com/26721/169638385-a8772837-39ac-4903-a985-2733fafde3e0.png)

**Comment by OBrink** [comment]
I am a bit afraid that DECIMER Segmentation is not going to yield results when a single chemical structure depiction is uploaded. 

Maybe the following workflow would be a solution:

If only one image is uploaded:
    Run segmentation
    If there are segmentation results:
        run OCSR engine on them
    else:
        run OCSR engine directly on original uploaded image
      
@Kohulan, what do you think?

**Comment by Kohulan** [comment]
@OBrink Yes I would agree to this option.

**Comment by OBrink** [comment]
@egonw @steinbeck @Kohulan 

As requested, it works now as described above. A user can upload a single image and DECIMER Segmentation will run. If DECIMER Segmentation yields results, they are fed to the OCSR engine. If DECIMER Segmentation does not yield results, the original image is fed to the OCSR engine.

I hope that this works as an intermediate solution, but I am looking forward to eventually replacing the segmentation model with a more sophisticated one that has been trained on more diverse data. The model that is running now has only been trained on whole pages from the Journal of Natural Products. Hence, the segmentation results can be poor when, for example, an image that only contains a reaction scheme is uploaded.
