### ISSUE TITLE
Certain molecule representation create the wrong result

### ISSUE THREAD

**Issue by professorCKone** [OBrink/DECIMER_Web#28]
![testmole](https://user-images.githubusercontent.com/78862999/169799902-5e94896e-c493-4d19-ac27-d4d4fcf68aca.png)
The numbers in the molecule are part of representation for NMR purposes. Number "5" is interpreted as "S" (sulfur). I guess this might have to do with the resolution of the png file.

**Comment by steinbeck** [comment]
Nice and very difficult example. In most cases, atom numbers are not placed directly on the atom position and then DECIMER does a good job, but this particular case will always be hard. Thanks for submitting. We'll see how future versions of DECIMER deal with this. As a first step, I suggest we create a high-res version of this and see how it copes.

**Comment by professorCKone** [comment]
Thank you for the quick feedback. I know that Decimer does a great job with regular structures. Let me create a high res version. This might do the trick.

Von: Christoph Steinbeck ***@***.***>
Datum: Montag, 23. Mai 2022 um 12:32
An: OBrink/DECIMER_Web ***@***.***>
Cc: Christian Kronseder ***@***.***>, Author ***@***.***>
Betreff: Re: [OBrink/DECIMER_Web] Certain molecule representation create the wrong result (Issue #28)

Nice and very difficult example. In most cases, atom numbers are not placed directly on the atom position and then DECIMER does a good job, but this particular case will always be hard. Thanks for submitting. We'll see how future versions of DECIMER deal with this. As a first step, I suggest we create a high-res version of this and see how it copes.

**Comment by Kohulan** [comment]
@professorCKone Could you kindly send us a High-resolution version of this image?

**Comment by professorCKone** [comment]
I don't have a hi-res version of the originla, which is exactly my problem. I tried to make NMR annotated gifs machine reabable, but had to give up due to the low resolution of the available images. It seems that numbers in a hi-res version don't bother your deep learning approach. The result is correct, but in order to be less guessing and more precise you need to test a few more I suppose. RDKit allows you to create molecules with numbers btw. Rgds Christian

**Comment by Kohulan** [comment]
@professorCKone 

Thanks a lot for this overall report, As you mentioned I could see that with the higher resolution Image decimer.ai works perfectly well.
<img width="1158" alt="image" src="https://user-images.githubusercontent.com/30716951/169822004-2a86f9c8-07ae-4b33-83fb-751cb3457431.png">

- https://pubchem.ncbi.nlm.nih.gov/compound/370

The problem here I could see is that in the original image the number "5" is too similar to the letter "S". We did implement molecules with atom numbers depicted within probably we should increase the augmentations on such numbers as well.

**Comment by professorCKone** [comment]
Other complications in lo-res are 6, 9 and 8, which can be read as O. I had several variations of this problem. Still well done from your side with decimer. 
We will have a closer look and see if we can integrate it in our electronic lab journal
Best regards,
Christian

**Comment by professorCKone** [comment]
Hi Christoph,
I have about 13'000 of those noisy pictures. The goal is to automatically interpret NMR spectra by using deep learning.

How about a quick video call and I can explain what I am working at?

Best
Christian

Von: Christoph Steinbeck ***@***.***>
Datum: Montag, 23. Mai 2022 um 17:01
An: OBrink/DECIMER_Web ***@***.***>
Cc: Christian Kronseder ***@***.***>, Mention ***@***.***>
Betreff: Re: [OBrink/DECIMER_Web] Certain molecule representation create the wrong result (Issue #28)
Christian, if you have an interesting data set of that type to OCSR, then there is of course always the possibility of retraining DECIMER with fabricated noisy, low-res images of the same type.
Annotated nmr data are close to our heart (if this is what this is :)) and we could try to work together on this.
If you want to take this off github, feel free to send me an email.

Cheers, Chris

—
Prof. Dr. Christoph Steinbeck
Analytical Chemistry - Cheminformatics and Chemometrics
Friedrich-Schiller-University Jena, Germany
Phone Secretariat: +49-3641-948171
http://cheminf.uni-jena.de
http://orcid.org/0000-0001-6966-0814

What is man but that lofty spirit - that sense of enterprise.
... Kirk, "I, Mudd," stardate 4513.3..

**Comment by OBrink** [comment]
I am going to close this issue here for now, as it technically is a problem of [the OCSR engine](https://github.com/Kohulan/DECIMER-Image_Transformer), and not a problem of the web application. We are continuously working on the further diversification of our training data in order to increase DECIMER's capabilities in future versions.
