### ISSUE TITLE
Replace transparent background in logos in Readme with white background

### ISSUE THREAD

**Issue by OBrink** [OBrink/DECIMER_Web#30]
Otherwise it looks a bit odd in dark mode.
![image](https://user-images.githubusercontent.com/59618901/175492333-8ae5ad61-dea4-4ddc-9e42-fe50b6de617b.png)

**Comment by Kohulan** [comment]
It uses the same images we are using for the website, Maybe I will upload new ones?

**Comment by OBrink** [comment]
The background of the website is white. Hence, the background appears white on the website. On Github in dark mode, is not white and the transparent background in the logos becomes obvious. If we just replace the background in the logos with white instead of transparent, everything should look as it's supposed to on the website and the repository.
