### ISSUE TITLE
Add DECIMER classifier to the web App

### ISSUE THREAD

**Issue by Kohulan** [OBrink/DECIMER_Web#33]
Check with @iagea

**Comment by OBrink** [comment]
Lovely. Thank you @Iagea for building, training and testing the classifier! 

(@zielesny @steinbeck @Kohulan)

![structure_fail](https://user-images.githubusercontent.com/59618901/179224914-34fde784-a415-4a5e-bc43-2c1a4a8f725e.png)
![structure_fail_2](https://user-images.githubusercontent.com/59618901/179225079-992c9235-fee7-44b7-b049-5fc335d21d30.png)
![image](https://user-images.githubusercontent.com/59618901/179225355-084b6201-2f3f-4e98-8295-dfd07fb81e74.png)
