### ISSUE TITLE
Segmentation makes website crash

### ISSUE THREAD

**Issue by OBrink** [OBrink/DECIMER_Web#4]
Bug report from Isa:

"Hi! I've been playing around with [decimer.ai](http://decimer.ai/) and I've found out that some articles crush the webpage. For example this one: https://pubs.acs.org/doi/10.1021/acs.jnatprod.0c00211. I've tried also the segments alone and it works so the problem is on the segmentation step."

**Comment by OBrink** [comment]
The problem appears to be a request timeout on the side of the Google Cloud server. The logs show no problems and the segments are actually generated. I have set a timer multiple times and it aborts exactly after 30 seconds.

**Comment by Kohulan** [comment]
It was a load balancer issue now solved. The current timeout is 300s.
