### ISSUE TITLE
Download SMILES also as from results

### ISSUE THREAD

**Issue by Kohulan** [OBrink/DECIMER_Web#46]
Currently, when you hit download only the mol files get downloaded, Generate a text file with the resulted SMILES strings.

**Comment by OBrink** [comment]
The web app now creates a file (results.smiles.txt) where the file names are mapped to the resolved SMILES representations. Tested and pushed to the server. 
__
Have a nice weekend!

**Comment by Kohulan** [comment]
Great ! Thanks a lot.
--
Have a wonderful weekend 😃
