### ISSUE TITLE
Fixing iPhone camera image upload

### ISSUE THREAD

**Issue by falfren** [OBrink/DECIMER_Web#49]
If using the webpage https://decimer.ai/ with iOS, the original photo file format - which is HEIF - might not be recognised and does not yield any prediction results. Encoding to a more suitable format like JPG prior processing might fix the issue.

**Comment by Kohulan** [comment]
@falfren Thank you we never thought about it I will make a note of it. Maybe this could also be a fix in [DECIMER-Image transformer](https://github.com/Kohulan/DECIMER-Image_Transformer) .

**Comment by OBrink** [comment]
Thank you for the feedback, @falfren! I am on holiday for two weeks from now on, but will make sure to look into it once I am back :)

**Comment by falfren** [comment]
@OBrink @Kohulan thank you for considering and having a look at it. :)

**Comment by Kohulan** [comment]
The bug is now fixed with the recent version of DECIMER [e7076f5](https://github.com/Kohulan/DECIMER-Image_Transformer/commit/e7076f52bb25788ff4e379e550fd5b19a3a9de61)
https://pypi.org/project/decimer/
