### ISSUE TITLE
In Safari, Ketcher window stays empty

### ISSUE THREAD

**Issue by OBrink** [OBrink/DECIMER_Web#6]
The SMILES str is displayed correctly but the structure is not loaded in the Ketcher window

**Comment by Kohulan** [comment]
We have to consult with ketcher app developers

**Comment by OBrink** [comment]
In the Safari console:

"TypeError: undefined is not an object (evaluating 'ketcher.setMolecule')

**Comment by OBrink** [comment]
I have filed an issue [here](https://github.com/epam/ketcher/issues/1549).

**Comment by OBrink** [comment]
The issue is solved with a modification of the loadMol function. It now checks whether or not the Ketcher window is loaded before trying to load a molecule. If it is not loaded, it waits 100ms and calls itself again.
